### ISSUE TITLE
Request for Fork Adoption & Question Regarding `data.json` Updates

### ISSUE THREAD

**Issue by C0pywriting** [KaiserRuben/Putzplan#1]
Hi,  

First off, thanks a lot for this repo! It’s super helpful and really well done. Great job putting this together!  

 ([TheyCallMeNobody/Putzplan](https://github.com/TheyCallMeNobody/Putzplan)) made a few changes that I think could improve the project. Would you be open to taking a look and maybe merging them into the main repo?  

Also, I have a quick question: How does the `data.json` file get updated in a running container when new tasks are added? Is there a specific way to handle this?  

Thanks in advance for your help! Looking forward to hearing from you.  

Cheers

**Comment by KaiserRuben** [comment]
Hi,

cool, I had a look, looks great, more time slots are always useful.
Feel free to create a pull request!

> Also, I have a quick question: How does the data.json file get updated in a running container when new tasks are added? Is there a specific way to handle this?

Currently, it doesn't. Because the pages are statically rendered, the data.json becomes part of the build.

In theory, I guess one could load it dynamically and then create a Docker volume for it 🤷🏻‍♂️

Greetings,

Ruben

**Comment by C0pywriting** [comment]
@TheyCallMeNobody can you create a pull request?

**Comment by TheyCallMeNobody** [comment]
Sure, I've just created one
